import { ChatRequest, ChatResponse } from "@/types/chat";
import { callDialogflow } from "@/nlp/dialogflow.client";
import { parseDialogflowResponse } from "@/nlp/intent.parser";
import { getAnswer } from "./knowledge";

const CONFIDENCE_THRESHOLD = 0.65; // Slightly lower for Dialogflow (can be adjusted)

export async function processChat(
  data: ChatRequest
): Promise<ChatResponse> {

  // Pass a unique ID for session if available or use default generated by client
  const rawDFResponse = await callDialogflow(data.message);
  
  // Parse the raw response into our standard contract
  const nlpResult = parseDialogflowResponse(rawDFResponse);

  console.log(`Parsed NLP Result: Intent='${nlpResult.intent}', Confidence=${nlpResult.confidence}`);

  // Fallback if the confidence is too low or intent is completely unknown
  if (nlpResult.intent === "unknown" || nlpResult.confidence < CONFIDENCE_THRESHOLD) {
    return {
      reply: getAnswer("fallback"),
      intent: nlpResult.intent,
      confidence: nlpResult.confidence,
    };
  }

  // Retrieve answer from Dialogflow natively or fallback to knowledge base
  const answer = nlpResult.fulfillmentText || getAnswer(nlpResult.intent);

  return {
    reply: answer,
    intent: nlpResult.intent,
    confidence: nlpResult.confidence,
  };
}